#アクション目標メッセージ（ゴール）：目標値（引数）
#---
#アクション結果メッセージ（結果）：主にTrue or Falseのブール値（返り値）
#---
#アクションフィードバックメッセージ（フィードバック）：途中経過の返り値

#pythonプログラム内の記述「戻り値response = self.client(引数)」。クライアントがsrvファイルで定義した引数（srvファイル内「---」の上側）を別ファイルのサーバーにリクエストし、サーバーからの返り値（srvファイル内「---」の下側）をresponseに代入

string action_request
---
bool check_finish_response
---
